### ISSUE TITLE
No files in constants folder

### ISSUE THREAD

**Issue by blastbeng** [gogaz/coach_royale#100]
Hi,
i am trying to configure your app but i have an error, looks like the app is trying to access /constants/arenas.json but in the constants folder there is no file named arenas.json, should i manually put something inside thid directory?

Thanks

**Comment by gogaz** [comment]
Hello,
I'm glad you tried to run the app, this file should be automatically pulled from RoyaleAPI during the first sync. If not, please reopen the issue
