### ISSUE TITLE
Unknown command: 'royaleapi_tournaments'

### ISSUE THREAD

**Issue by blastbeng** [gogaz/coach_royale#101]
When executing:

/usr/bin/python3 manage.py royaleapi_tournaments --open   
              
I get:                                                                                                                      
Unknown command: 'royaleapi_tournaments'. Did you mean royaleapi_pull_clans?                                                                                                                                      
Type 'manage.py help' for usage.

**Comment by gogaz** [comment]
This command has been removed in commit c795dc945960e41a0963a053b3516482a47bc211 as of RoyaleAPI
