### ISSUE TITLE
image "coach_royale_base" has been removed.

### ISSUE THREAD

**Issue by RoyLaw** [gogaz/coach_royale#165]
During the setting up, it showed:
Pulling celery-beat (coach_royale_base:)...
ERROR: The image for the service you're trying to recreate has been removed. If you continue, volume data could be lost. Consider backing up your data before continuing.

**Comment by gogaz** [comment]
Hey, thanks for sharing! That is a weird thing, can you share exactly the steps that led you to this error?

**Comment by RoyLaw** [comment]
Thanks. Running docker-compose build backend is helpful.
